import Head from 'next/head'
import { useState, useEffect } from 'react'
import useLayoutEffect from '../hooks/useIsomorphicLayoutEffect'
import {
  Navbar,
  Hero,
  About,
  Experiences,
  Skills,
  Projects,
  Footer,
} from '../components'
import useTheme from '../hooks/useTheme'

const App = () => {
  const { isDarkMode, setIsDarkMode } = useTheme()
  const [isFirstRender, setIsFirstRender] = useState(true)

  useLayoutEffect(() => {
    const theme = JSON.parse(localStorage.getItem('theme'))

    if (theme !== null) {
      setIsDarkMode(theme)
    }

    if (isFirstRender) setIsFirstRender(false)
  }, [])

  useEffect(() => {
    const obeserver = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add('show')
        }
      })
    })

    const hiddenElements = document.querySelectorAll('.hidden')
    hiddenElements.forEach((el) => obeserver.observe(el))
  }, [])

  const toggleDarkMode = () => {
    setIsDarkMode(!isDarkMode)
    localStorage.setItem('theme', !isDarkMode)
  }

  return (
    <div
      className={`container${isDarkMode ? ' theme--dark' : ' theme--light'}`}
      id='home'
    >
      <Head>
        <title>Erlangga&apos;s Journey</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar isDarkMode={isDarkMode} toggleDarkMode={() => toggleDarkMode()} />
      <Hero />
      <About />
      <Experiences />
      <Skills />
      <Projects />
      <Footer />
    </div>
  )
}

export default App
